# Question 1 Answer:

In [3]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2 Answer:

In [12]:
l1=[]
n=5
print("enter the values for list1")
for i in range(0,n):
    nn=int(input())
    l1.append(nn)
    
l2=[]
print("enter the values for list2")
for i in range(0,n):
    nm=int(input())
    l2.append(nm)

aa=np.array(l1)
bb=np.array(l2)

cc=np.concatenate((aa,bb))
print("concatenated array\n",cc)
print("sorted array\n",np.sort(cc))

enter the values for list1
20
10
90
40
30
enter the values for list2
40
60
10
2
34
concatenated array
 [20 10 90 40 30 40 60 10  2 34]
sorted array
 [ 2 10 10 20 30 34 40 40 60 90]


# Question 3 Answer:

In [23]:
ar=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("dimensions is",np.ndim(ar))
print("size of array is",ar.size)

dimensions is 1
size of array is 12


# Question 4 Answer:

In [34]:
darr=np.array([1,2,3,4,5,6]).reshape(2,3)
print("2darr is\n",darr[np.newaxis])
print(darr[np.newaxis].shape)
print("2darr is\n",np.expand_dims(darr,0))
print(np.expand_dims(darr,0).shape)

2darr is
 [[[1 2 3]
  [4 5 6]]]
(1, 2, 3)
2darr is
 [[[1 2 3]
  [4 5 6]]]
(1, 2, 3)


# Question 5 Answer:

In [36]:
snpar1=np.array([[1,2],[3,4]])
snpar2=np.array([[5,6],[7,8]])
print("Vertical Stacking\n",np.vstack((snpar1,snpar2)))
print("Horoizontal Stacking\n",np.hstack((snpar1,snpar2)))

Vertical Stacking
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horoizontal Stacking
 [[1 2 5 6]
 [3 4 7 8]]


# Question 6 Answer:

In [9]:
import numpy as np
arr=np.array([10,20,30,30,30,40,50,50,60,70,80,90])
uval=np.unique(arr)
print("unique values\n",uval)
print("total unique values\n",np.size(uval))

unique values
 [10 20 30 40 50 60 70 80 90]
total unique values
 9
